# Generated by Django 4.2.1 on 2024-07-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitySearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=255)),
                ('search_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='usersearch',
            name='last_city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usersearch',
            name='session_key',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='usersearch',
            name='search_history',
            field=models.ManyToManyField(blank=True, related_name='user_searches', to='weather.citysearch'),
        ),
    ]
